title: "Dr. Pavel Koprov"
email: "koprovp@gmail.com"
description: >- 
  Senior R&D Engineer | Robotics | Digital Twins | Industrial AI
baseurl: ""
url: "https://pkoprov.github.io"
remote_theme: "mmistakes/minimal-mistakes"

author:
  name: "Pavel Koprov"
  bio: "Senior R&D Engineering Specialist at The Dow Chemical Company  | PhD in Industrial Engineering: Advanced Manufacturing"
  avatar: "/assets/images/yourphoto.jpg"
  links:
    - label: "LinkedIn"
      url: "https://www.linkedin.com/in/pkoprov/"
    - label: "GitHub"
      url: "https://github.com/pkoprov"
    - label: "Google Scholar"
      url: "https://scholar.google.com/citations?user=YOUR_ID"
    - label: "CV"
      url: "/cv/"

header_pages:
  - about.md
  - cv.md
  - projects.md
  - publications.md

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
